version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: mvc-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:latest
    container_name: mvc-nginx
    restart: always
    ports:
      - 8008:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: mvc-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  mailhog:
    container_name: mvc-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8022:8025"
      - "1022:1025"